services:
  - type: web
    name: rooc-auction-bot
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_TYPE
        value: postgres
      - key: PORT
        value: 10000
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_CALLBACK_URL
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_ANNOUNCE_CHANNEL_ID
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
