services:
  - type: web
    name: rooc-auction-bot
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_TYPE
        value: postgres
      - key: PORT
        value: 10000
      - fromContext: true
        key: DISCORD_TOKEN
      - fromContext: true
        key: DISCORD_CLIENT_ID
      - fromContext: true
        key: DISCORD_CLIENT_SECRET
      - fromContext: true
        key: DISCORD_CALLBACK_URL
      - fromContext: true
        key: DISCORD_GUILD_ID
      - fromContext: true
        key: DISCORD_ANNOUNCE_CHANNEL_ID
      - fromContext: true
        key: SESSION_SECRET
      - fromContext: true
        key: DATABASE_URL
